name: Wheel builder
on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check Python version
        run: python --version

      - name: Download Python package source files
        run: "pip wheel ${{ github.event.issue.title }}"

      - name: Check contents
        run: ls

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.issue.title }}
          path: "*"
