name: Wheel builder
on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Python version
        run: python --version

      - name: Build wheel
        run: "pip wheel ${{ github.event.issue.title }}"

      - name: Check contents
        run: ls
        
      - name: Config git
        run: |
          git config --global user.name Sygmei
          git config --global user.email "3835355+Sygmei@users.noreply.github.com" 

      - name: Push changes
        run: 'git add . && git commit -m "added package ${{ github.event.issue.title }}" && git push'
